name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip ninja-build
        pip3 install meson
        sudo apt-get install -y libvulkan-dev
        sudo apt-get install -y libglfw3-dev
        sudo apt-get install -y libglm-dev
        sudo apt-get install -y xvfb
    - name: Configure with Meson
      run: meson setup builddir
    - name: Build with Ninja
      run: ninja -C builddir
    - name: Run executable
      run: |
        export DISPLAY=:99
        /usr/bin/Xvfb :99 -screen 0 1280x720x24 &
        sleep 5
        timeout 5s ./builddir/VulkanEngine || true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: VulkanEngine
        path: builddir/VulkanEngine
        #warn: Output a warning but do not fail the action
        #error: Fail the action with an error message
        #ignore: Do not output any warnings or errors, the action does not fail
        #if-no-files-found: #optional
        # Duration after which artifact will expire in days. 0 means using default retention. Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
    
        #retention-days: # optional
        # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.
    
        #compression-level: # optional, default is 6
        # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.
    
        #overwrite: # optional, default is false
        # If true, hidden files will be included in the artifact. If false, hidden files will be excluded from the artifact.
    
        #include-hidden-files: # optional, default is false
